version: '3.8'

services:
  duckdb-rest-server1:
    build: ../../duckdb-rest-server
    container_name: duckdb-rest-server1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_INIT_SQL_PATH=/tmp/init.sql
    ports:
      - "8081:8080"
    volumes:
      - ./init.sql:/tmp/init.sql:ro      
    networks:
      - backend

  duckdb-rest-server2:
    build: ../../duckdb-rest-server
    container_name: duckdb-rest-server2
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_INIT_SQL_PATH=/tmp/init.sql
    ports:
      - "8082:8080"
    volumes:
      - ./init.sql:/tmp/init.sql:ro            
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - duckdb-rest-server1
      - duckdb-rest-server2
    networks:
      - backend

networks:
  backend:
    driver: bridge